name: toodoo
description: A Full fledged task manager application using Flutter + Firebase + Coffee.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # lottie: ^1.2.1
  # intl: ^0.17.0
  # flutter_native_splash: ^2.0.1+1

# Uncomment the following lines if you wish to generate splash screens
#
# flutter_native_splash:
#   color: "#ffffff"
#   image: "assets/"
#   color_dark: "#222831"
#   image_dark: "assets/"
#   android: true
#   ios: true
#
# command : flutter pub run flutter_native_splash:create

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  # build_runner: ^2.1.4
  # json_serializable: ^5.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/Icons/
    - assets/Images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/Fonts/Nunito/nunito_light.ttf
          weight: 300
        - asset: assets/Fonts/Nunito/nunito_regular.ttf
          weight: 400
        - asset: assets/Fonts/Nunito/nunito_semi_bold.ttf
          weight: 600
        - asset: assets/Fonts/Nunito/nunito_bold.ttf
          weight: 700
        - asset: assets/Fonts/Nunito/nunito_extra_bold.ttf
          weight: 800
